### ISSUE TITLE
[Question] similarity

### ISSUE THREAD

**Issue by robsonpeixoto** [codelibs/minhash#1]
On README.md you put this case:

```
// Compare a different text.
String text2 = "Solr is the popular, blazing fast open source enterprise search platform";
byte[] minhash2 = MinHash.calculate(analyzer, text2);
assertEquals(0.453125f, MinHash.compare(minhash, minhash2));
```

Please, help-me to understand this algorithm. Why the compare of two very different string the value is `0.453125f`. Why not a number more near to `0`?

Thanks

**Comment by marevol** [comment]
MinHash discriminates a high similarity(90% match or above), but cannot detect other one. Therefore, for different strings, I think that the value is about 0.5. So, it's stochastic...

**Comment by robsonpeixoto** [comment]
Thanks @marevol. Do you recommend a article/paper to understand better the algorithm parameters?
